sudo: required
services:
  - docker

before_install:
  - docker build -t hshinde1301/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hshinde1301/docker-react npm run test -- --coverage 
